feat(user feedback): count lam as an embedded cluster artifact (#4703)
instead of showing lam image push in a different section of the kots
output we should count it as part of the embedded cluster artifacts.

output:
```
root@bold-sky:/home/dev# ./kots install embedded-cluster-smoke-test-staging-app/ci-airgap --license-file ./license.yaml --namespace kotsadm --app-version-label appver-dev-c51b55a --exclude-admin-console --airgap-bundle ./embedded-cluster-smoke-test-staging-app.airgap
  • Validating registry information ✓
  • Deploying application
Pushing application images (1/1)
Pushing image 10.96.0.11:5000/embedded-cluster-smoke-test-staging-app/nginx:1.24-alpine
Copying blob da33b1ad0ac4 skipped: already exists
Copying blob 16eaaaf5f1c0 skipped: already exists
Copying blob b407bcc80638 skipped: already exists
Copying blob a0fbd691d7c1 skipped: already exists
Copying blob 3c854c8cbf46 skipped: already exists
Copying blob de5d475193dd skipped: already exists
Copying blob 5e845cc16269 skipped: already exists
Copying config 249f59e1de done   |
Writing manifest to image destination
Pushing embedded cluster artifacts (1/7)
Pushing image 10.96.0.11:5000/embedded-cluster-smoke-test-staging-app/embedded-cluster/embedded-cluster-local-artifact-mirror:dev-c51b55a
Copying blob 4ea89e459bc7 skipped: already exists
Copying blob dc4977db5b1f skipped: already exists
Copying config 0ed66a3165 done   |
Writing manifest to image destination
Pushing embedded cluster artifacts (2/7)
Pushing embedded cluster artifacts (3/7)
Pushing embedded cluster artifacts (4/7)
Pushing embedded cluster artifacts (5/7)
Pushing embedded cluster artifacts (6/7)
Pushing embedded cluster artifacts (7/7)
  • Waiting for Admin Console to be ready ✓
  • Uploading app archive
  • Waiting for installation to complete ✗
Error: failed to validate installation: license already exists for app embedded-cluster-smoke-test-staging-app
root@bold-sky:/home/dev#
```